on:
  push:
    branches: [ main ]
    paths-ignore:
  pull_request:
    branches: [ main ]
  schedule:
    - cron '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
steps:
  - run: |
    echo "    This job was triggered by event: {{ github.event_name }} 
    echo "    Then anme of your branch is ${{ github.ref }} and your repo is ${{ github.repository }} 
